name: Deploy React to Hostinger via SSH

on:
  push:
    branches:
      - main  # Se ejecutará cuando hagas push en main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 65002 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ls -la ~/.ssh/   # 🔹 Verifica si la clave se guardó correctamente
          head -n 5 ~/.ssh/id_rsa  # 🔹 Muestra las primeras líneas de la clave privada para depuración
        shell: bash

      - name: Deploy to Hostinger via Rsync
        run: rsync -e "ssh -p 65002" -avz --delete dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/public_html/
